  try {
    let a = 0
   
    console.log(b)
  }catch(err){
    console.log(err.message)
   
  }
  finally{
    console.log("heyy")
  } 

